"""
Mirror spheresofpower.wikidot.com into an Obsidian / Quartz compatible Markdown vault.

Two stages:
  fetch    -> downloads raw HTML for every page in the sitemap into .cache/raw/ (resumable;
              only re-downloads pages whose sitemap lastmod is newer than the cached copy)
  convert  -> turns cached HTML into Markdown under content/ with [[wikilinks]], frontmatter,
              tags, and folder structure from the wiki's breadcrumbs

Usage:
  python scripts/scrape.py              # fetch + convert
  python scripts/scrape.py fetch
  python scripts/scrape.py convert
  python scripts/scrape.py --images     # also download wiki-hosted images (product art; see README)
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import json
import re
import shutil
import sys
import time
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

import requests
from bs4 import BeautifulSoup, NavigableString, Tag
from markdownify import MarkdownConverter

SITE = "https://spheresofpower.wikidot.com"
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cache"
RAW = CACHE / "raw"
CONTENT = ROOT / "content"
ATTACH = CONTENT / "attachments"
UA = "Mozilla/5.0 (personal OGL archive mirror; low request rate)"

# Wikidot plumbing pages that carry no game content.
SKIP_PREFIXES = ("admin:", "forum:", "system:", "search:", "deleted:", "nav:top")
SKIP_EXACT = {"_template", "legal:privacy-policy", "legal:terms-of-use"}  # last two are Wikidot's own policies
GENERATED_MARK = "<!-- generated by scripts/scrape.py -->"

session = requests.Session()
session.headers["User-Agent"] = UA


# --------------------------------------------------------------------------- fetch

def sitemap() -> dict[str, str]:
    xml = session.get(f"{SITE}/sitemap.xml", timeout=60).text
    pages = {}
    for m in re.finditer(r"<url><loc>([^<]+)</loc>(?:<lastmod>([^<]+)</lastmod>)?", xml):
        slug = m.group(1).replace(SITE, "").strip("/") or "start"
        if slug in SKIP_EXACT or slug.startswith(SKIP_PREFIXES) or slug.endswith(":_template"):
            continue
        pages[slug] = m.group(2) or ""
    return pages


def cache_path(slug: str) -> Path:
    return RAW / (slug.replace(":", "__") + ".html")


def fetch_one(slug: str) -> tuple[str, str]:
    for attempt in range(5):
        try:
            r = session.get(f"{SITE}/{slug}", timeout=60)
            if r.status_code == 200:
                cache_path(slug).write_text(r.text, encoding="utf-8")
                return slug, "ok"
            if r.status_code == 404:
                return slug, "404"
        except requests.RequestException:
            pass
        time.sleep(2 ** attempt)
    return slug, "failed"


def fetch(workers: int = 4) -> None:
    RAW.mkdir(parents=True, exist_ok=True)
    pages = sitemap()
    manifest_file = CACHE / "manifest.json"
    manifest = json.loads(manifest_file.read_text()) if manifest_file.exists() else {}

    todo = [s for s, mod in pages.items()
            if not cache_path(s).exists() or manifest.get(s) != mod]
    print(f"{len(pages)} pages in sitemap, {len(todo)} to download")

    done = 0
    failed = []
    with cf.ThreadPoolExecutor(workers) as pool:
        for slug, status in pool.map(fetch_one, todo):
            done += 1
            if status == "ok":
                manifest[slug] = pages[slug]
            else:
                failed.append((slug, status))
            if done % 100 == 0:
                print(f"  {done}/{len(todo)}")
                manifest_file.write_text(json.dumps(manifest, indent=0))
    manifest_file.write_text(json.dumps(manifest, indent=0))
    (CACHE / "pages.json").write_text(json.dumps(sorted(pages)))
    if failed:
        print("Failed:", failed)


# --------------------------------------------------------------------------- convert

def clean_filename(name: str) -> str:
    name = re.sub(r'[\\/:*?"<>|#^\[\]]', "", name)  # illegal on Windows or meaningful to Obsidian links
    name = re.sub(r"\s+", " ", name).strip(" .")
    return name[:120] or "untitled"


class Page:
    def __init__(self, slug: str, html: str):
        self.slug = slug
        soup = BeautifulSoup(html, "lxml")
        t = soup.select_one("#page-title")
        self.title = t.get_text(" ", strip=True) if t else ""
        if not self.title:
            self.title = slug.split(":")[-1].replace("-", " ").title()
        if slug == "start":
            self.title = "Spheres of Power Wiki"
        elif slug == "nav:side":
            self.title = "Wiki Navigation"
        elif slug == "legal:start":
            self.title = "Legal and Open Game License"
        crumbs = soup.select("#breadcrumbs a")
        self.parents = [a["href"].strip("/") for a in crumbs if a.get("href", "").startswith("/")]
        self.parents = [p for p in self.parents if p != "start"]
        self.tags = [a.get_text(strip=True) for a in soup.select(".page-tags a")
                     if a.get_text(strip=True) and not a.get_text(strip=True).startswith("_")]
        self.body = soup.select_one("#page-content")
        # anchor id -> heading text, so cross-page #toc links can become [[Page#Heading]]
        self.anchors: dict[str, str] = {}
        if self.body:
            for h in self.body.find_all(re.compile("^h[1-6]$")):
                if h.get("id"):
                    self.anchors[h["id"]] = heading_text(h)
            for a in self.body.find_all("a", attrs={"name": True}):
                nxt = a.find_next(re.compile("^h[1-6]$"))
                if nxt:
                    self.anchors[a["name"]] = heading_text(nxt)
        self.folder = ""
        self.filename = ""


def heading_text(h: Tag) -> str:
    return re.sub(r"[#^\[\]|]", "", h.get_text(" ", strip=True)).strip()


class WikiConverter(MarkdownConverter):
    """markdownify with wikidot-aware link/table/image handling."""

    def __init__(self, page: Page, pages: dict[str, Page], images: dict[str, str], **kw):
        super().__init__(heading_style="ATX", bullets="-", escape_underscores=False,
                         escape_asterisks=False, **kw)
        self.page, self.pages, self.images = page, pages, images

    # --- links
    def convert_a(self, el, text, *args, **kw):
        href = el.get("href", "")
        text = text.strip()
        if not href or href.startswith("javascript:"):
            return text
        if href.startswith("#"):
            target = self.page.anchors.get(href[1:])
            return f"[[#{target}|{text}]]" if target else text
        parsed = urllib.parse.urlparse(href)
        internal = (not parsed.netloc) or parsed.netloc.endswith("spheresofpower.wikidot.com")
        if internal and "local--files" not in parsed.path:
            slug = urllib.parse.unquote(parsed.path.strip("/")) or "start"
            slug = slug.lower()
            target = self.pages.get(slug)
            if target:
                frag = ""
                if parsed.fragment:
                    h = target.anchors.get(parsed.fragment)
                    frag = f"#{h}" if h else ""
                label = text.replace("|", "\\|").replace("[", "(").replace("]", ")")
                if not label or (label == target.filename and not frag):
                    return f"[[{target.filename}{frag}]]"
                return f"[[{target.filename}{frag}|{label}]]"
            # links to pages that don't exist on the wiki ("red links") -> plain text
            if not parsed.netloc:
                return text
        if not href.startswith("http"):
            href = SITE + href
        return f"[{text}]({href})" if text else f"<{href}>"

    # --- images
    def convert_img(self, el, text, *args, **kw):
        src = el.get("src", "")
        alt = el.get("alt", "") or Path(urllib.parse.unquote(src)).name
        if src in self.images:
            return f"![[{self.images[src]}]]"
        return f"[image: {urllib.parse.unquote(alt)}]({src})"

    # --- tables: keep cells single-line so the markdown table survives
    def convert_td(self, el, text, *args, **kw):
        text = re.sub(r"\s*\n\s*", " <br> ", text.strip()).replace("|", "\\|")
        text = re.sub(r"(\s*<br>\s*)+$", "", text)
        colspan = int(el.get("colspan", 1) or 1)
        return " " + text + " |" + " |" * (colspan - 1)

    convert_th = convert_td


def preprocess(body: Tag, soup_factory) -> None:
    """Rewrite wikidot widgets into plain HTML that markdownify understands."""
    for sel in ["#toc", "script", "style", ".wd-adunit", "iframe", ".page-tags",
                ".footnotes-footer .title", ".printuser"]:
        for el in body.select(sel):
            el.decompose()

    # Tabviews: each tab becomes a bold heading followed by its content.
    for nav in body.select(".yui-navset"):
        labels = [li.get_text(" ", strip=True) for li in nav.select(".yui-nav li")]
        panes = nav.select(".yui-content > div")
        wrapper = soup_factory.new_tag("div")
        for label, pane in zip(labels, panes):
            h = soup_factory.new_tag("h4")
            h.string = label
            wrapper.append(h)
            wrapper.append(pane)
        nav.replace_with(wrapper)

    # Collapsibles: drop the "show/hide" toggles, keep the unfolded content with its label.
    for block in body.select(".collapsible-block"):
        link = block.select_one(".collapsible-block-folded a")
        label = link.get_text(" ", strip=True) if link else ""
        label = re.sub(r"^[+\-]\s*", "", label)
        content = block.select_one(".collapsible-block-content")
        wrapper = soup_factory.new_tag("div")
        if label and not re.match(r"(?i)^(show|hide)\b", label):
            p = soup_factory.new_tag("p")
            b = soup_factory.new_tag("strong")
            b.string = label
            p.append(b)
            wrapper.append(p)
        if content:
            wrapper.append(content)
        block.replace_with(wrapper)

    # Footnote refs: <sup class="footnoteref"><a>1</a></sup> -> [^1]
    for sup in body.select("sup.footnoteref"):
        sup.replace_with(NavigableString(f"[^{sup.get_text(strip=True)}]"))
    footer = body.select_one(".footnotes-footer")
    if footer:
        lines = []
        for fn in footer.select(".footnote-footer"):
            a = fn.find("a")
            num = a.get_text(strip=True) if a else str(len(lines) + 1)
            if a:
                a.decompose()
            lines.append(f"[^{num}]: {fn.get_text(' ', strip=True).lstrip('. ')}")
        footer.replace_with(NavigableString("\n\n" + "\n".join(lines) + "\n\n" if lines else ""))

    # Wikidot's colored spans / "redtext" etc. are just styling; unwrap.
    for span in body.find_all("span"):
        span.unwrap()

    # Store boxes: cover image linking to a shop + <strong>Book</strong> + price -> "Source: [Book](shop)".
    for img in body.find_all("img"):
        a = img.parent if img.parent and img.parent.name == "a" else None
        if not a or not a.get("href", "").startswith("http"):
            continue
        box = a.parent
        name = a.find_next_sibling("strong")
        if box and box.parent and name and "$" in box.get_text():
            p = soup_factory.new_tag("p")
            em = soup_factory.new_tag("em")
            em.append("Source: ")
            link = soup_factory.new_tag("a", href=a["href"])
            link.string = name.get_text(" ", strip=True)
            em.append(link)
            p.append(em)
            box.replace_with(p)

    # Tables: real data tables stay markdown tables; layout tables and navboxes get flattened.
    for table in reversed(body.find_all("table")):
        if table.parent is None:
            continue
        if is_layout_table(table):
            flatten_table(table, soup_factory)


def is_layout_table(table: Tag) -> bool:
    if "wiki-content-table" not in (table.get("class") or []):
        return True
    rows = table.find_all("tr", recursive=False) or table.select(":scope > tbody > tr")
    widths = [sum(int(c.get("colspan", 1) or 1) for c in r.find_all(["td", "th"], recursive=False))
              for r in rows]
    if not widths or max(widths) < 3:
        return False
    # Navbox: some rows are one cell spanning the table, and the content is basically all links.
    spanning = sum(1 for r in rows if len(r.find_all(["td", "th"], recursive=False)) == 1)
    text = table.get_text(" ", strip=True)
    link_text = " ".join(a.get_text(" ", strip=True) for a in table.find_all("a"))
    return spanning >= 2 and len(link_text) > 0.6 * max(len(text), 1)


def flatten_table(table: Tag, soup_factory) -> None:
    out = soup_factory.new_tag("div")
    rows = table.find_all("tr")
    for tr in rows:
        if tr.find_parent("table") is not table:
            continue
        cells = [c for c in tr.find_all(["td", "th"], recursive=False) if c.get_text(strip=True) or c.find("img")]
        if not cells:
            continue
        if len(cells) == 1:
            cell = cells[0]
            # a lone short cell with no links in a navbox is a section label
            if len(rows) > 1 and not cell.find(["a", "p", "ul", "table"]) and len(cell.get_text(strip=True)) < 60:
                p = soup_factory.new_tag("p")
                b = soup_factory.new_tag("strong")
                b.string = cell.get_text(" ", strip=True)
                p.append(b)
                out.append(p)
            else:
                div = soup_factory.new_tag("div")
                for child in list(cell.contents):
                    div.append(child)
                out.append(div)
        else:
            p = soup_factory.new_tag("p")
            for i, cell in enumerate(cells):
                if i:
                    p.append(" · ")
                for child in list(cell.contents):
                    p.append(child)
            out.append(p)
    table.replace_with(out)


def tidy(md: str) -> str:
    md = md.replace(" ", " ")
    md = re.sub(r"[ \t]+\n", "\n", md)
    md = re.sub(r"\n{3,}", "\n\n", md)
    # markdownify emits "**  text**" when the bold had padding
    md = re.sub(r"\*\*[ \t]+([^*\n]+?)[ \t]*\*\*", r"**\1**", md)
    # "<strong>Prerequisites:</strong>Text" -> bold label must be followed by a space to render
    md = re.sub(r"(\*\*[^*\n]*?[:.]\*\*)(?=[\w(\[])", r"\1 ", md)
    return md.strip() + "\n"


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def assign_paths(pages: dict[str, Page]) -> None:
    """Folder = top-level breadcrumb ancestor's title; filename = page title (deduped)."""
    used: dict[str, str] = {}
    for p in sorted(pages.values(), key=lambda p: p.slug):
        if p.slug == "start":
            p.folder, p.filename = "", "index"
            continue
        if p.slug.startswith(("legal:", "nav:")):
            p.folder = "Meta"
        elif p.parents and p.parents[0] in pages:
            p.folder = clean_filename(pages[p.parents[0]].title)
        else:
            p.folder = ""
        name = clean_filename(p.title)
        if name.lower() in used or name.lower() == "index":
            name = clean_filename(f"{p.title} ({p.slug.replace(':', '-')})")
        used[name.lower()] = p.slug
        p.filename = name
    # Top-level hub pages live inside the folder named after them.
    folders = {p.folder for p in pages.values()}
    for p in pages.values():
        if p.folder or p.slug == "start":
            continue
        if p.filename in folders:
            p.folder = p.filename
        elif "archetype" in p.title.lower():
            p.folder = "Archetypes (Unsorted)"
        else:
            p.folder = "Other Pages"


def download_images(pages: dict[str, Page]) -> dict[str, str]:
    ATTACH.mkdir(parents=True, exist_ok=True)
    mapping = {}
    for p in pages.values():
        if not p.body:
            continue
        for img in p.body.find_all("img"):
            src = img.get("src", "")
            if "local--files" not in src:
                continue
            name = clean_filename(urllib.parse.unquote(src.split("/")[-1]))
            dest = ATTACH / name
            if not dest.exists():
                try:
                    r = session.get(src.replace("http://", "https://"), timeout=60)
                    if r.ok:
                        dest.write_bytes(r.content)
                except requests.RequestException:
                    continue
            if dest.exists():
                mapping[src] = name
    return mapping


def convert(with_images: bool) -> None:
    slugs = [s for s in json.loads((CACHE / "pages.json").read_text())
             if s not in SKIP_EXACT and not s.startswith(SKIP_PREFIXES)]
    pages: dict[str, Page] = {}
    for slug in slugs:
        f = cache_path(slug)
        if f.exists():
            pages[slug] = Page(slug, f.read_text(encoding="utf-8"))
    assign_paths(pages)
    images = download_images(pages) if with_images else {}
    manifest = json.loads((CACHE / "manifest.json").read_text())

    # Remove previously generated notes (but never hand-written ones) so renames don't leave orphans.
    for old in CONTENT.rglob("*.md"):
        try:
            if GENERATED_MARK in old.read_text(encoding="utf-8"):
                old.unlink()
        except OSError:
            pass

    for p in pages.values():
        if not p.body:
            continue
        preprocess(p.body, BeautifulSoup("", "lxml"))
        md = WikiConverter(p, pages, images).convert_soup(p.body)
        fm = ["---", f"title: {yaml_str(p.title)}"]
        if p.filename != p.title:
            fm.append(f"aliases: [{yaml_str(p.title)}]")
        tags = sorted({re.sub(r'[^\w/-]', '-', t).strip('-') for t in p.tags} - {""})
        if tags:
            fm.append("tags: [" + ", ".join(yaml_str(t) for t in tags) + "]")
        fm.append(f"source: {SITE}/{p.slug}")
        if manifest.get(p.slug):
            fm.append(f"updated: {manifest[p.slug][:10]}")
        if p.parents:
            fm.append("parent: " + yaml_str(f"[[{pages[p.parents[-1]].filename}]]"
                                            if p.parents[-1] in pages else p.parents[-1]))
        fm.append("---")
        out = "\n".join(fm) + "\n" + GENERATED_MARK + "\n\n" + tidy(md)
        dest = CONTENT / p.folder / f"{p.filename}.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(out, encoding="utf-8")

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    (CACHE / "last-convert.txt").write_text(stamp)
    print(f"Wrote {len(pages)} notes to {CONTENT} ({stamp})")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", nargs="?", choices=["fetch", "convert", "all"], default="all")
    ap.add_argument("--images", action="store_true", help="download wiki-hosted images")
    ap.add_argument("--workers", type=int, default=4)
    a = ap.parse_args()
    if a.stage in ("fetch", "all"):
        fetch(a.workers)
    if a.stage in ("convert", "all"):
        convert(a.images)
