"""
Mirror spheresofpower.wikidot.com into an Obsidian / Quartz compatible Markdown vault.

Two stages:
  fetch    -> downloads raw HTML for every page in the sitemap into .cache/raw/ (resumable;
              only re-downloads pages whose sitemap lastmod is newer than the cached copy)
  convert  -> turns cached HTML into Markdown under content/ with [[wikilinks]], frontmatter,
              tags, and folder structure from the wiki's breadcrumbs

Usage:
  python scripts/scrape.py              # fetch + convert
  python scripts/scrape.py fetch
  python scripts/scrape.py convert
  python scripts/scrape.py --images     # also download wiki-hosted images (product art; see README)
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import html
import json
import re
import shutil
import sys
import time
import urllib.parse
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

import requests
from bs4 import BeautifulSoup, NavigableString, Tag
from markdownify import MarkdownConverter

SITE = "https://spheresofpower.wikidot.com"
ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / ".cache"
RAW = CACHE / "raw"
CONTENT = ROOT / "content"
ATTACH = CONTENT / "attachments"
UA = "Mozilla/5.0 (personal OGL archive mirror; low request rate)"

# Wikidot plumbing pages that carry no game content.
SKIP_PREFIXES = ("admin:", "forum:", "system:", "search:", "deleted:", "nav:top")
SKIP_EXACT = {"_template", "legal:privacy-policy", "legal:terms-of-use"}  # last two are Wikidot's own policies
GENERATED_MARK = "<!-- generated by scripts/scrape.py -->"

# Book lines left out of the mirror entirely: these top-level folders (hub page + everything under it)
# aren't converted, and links to them are removed from the navigation pages.
EXCLUDED_SECTIONS = {
    "Akashic Mysteries", "Arcforge", "City of 7 Seraphs", "Cthulhu Mythos", "Gonzo",
    "Heroes Of The Jade Oath", "Legendary Worlds", "Pact Magic", "Strange Magic",
    # pre-Ultimate copies; each has a current equivalent (its "Original" tab), and links to
    # them are redirected there (see old_page_redirects)
    "Spheres Of Power (Old)",
}
# Individual pages left out along with everything under them (by wikidot slug):
# Lost Spheres Publishing's classes ("Lost Champions").
EXCLUDED_PAGES = {"dragoon-class", "mountebank", "necros", "reaper"}
NAV_PAGES = {"start", "nav:side"}

# Home page: with the archetypes now a full-width table, move these sections (by their bold
# heading) to the end of the given column of the main navigation grid to even out the columns.
# Balanced from rendered section heights at 1920px (columns end up within ~330px of each other).
HOME_SECTION_MOVES = [
    ("Other Options", 2),
    ("Gear", 3),
    ("Practitioner Gear", 3),
    ("Feat Types", 4),
    ("Creatures", 5),
    ("Sample Practitioners", 5),
    ("Sample Champions", 5),
]

# The wiki colors links by product line with inline <span style="color:...">. Power is the default
# (uncolored) link color. Every link to a page gets its family's color (see data/link-families.json).
COLOR_FAMILIES = {
    "#4b0092": "guile",
    "#b900fe": "guile-alt",
    "#993300": "might",
    "#00c000": "champion",
}
FAMILY_FILE = ROOT / "data" / "link-families.json"
OBSIDIAN_SNIPPET = CONTENT / ".obsidian" / "snippets" / "sop-link-colors.css"

session = requests.Session()
session.headers["User-Agent"] = UA


# --------------------------------------------------------------------------- fetch

def sitemap() -> dict[str, str]:
    xml = session.get(f"{SITE}/sitemap.xml", timeout=60).text
    pages = {}
    for m in re.finditer(r"<url><loc>([^<]+)</loc>(?:<lastmod>([^<]+)</lastmod>)?", xml):
        slug = m.group(1).replace(SITE, "").strip("/") or "start"
        if slug in SKIP_EXACT or slug.startswith(SKIP_PREFIXES) or slug.endswith(":_template"):
            continue
        pages[slug] = m.group(2) or ""
    return pages


def cache_path(slug: str) -> Path:
    return RAW / (slug.replace(":", "__") + ".html")


def fetch_one(slug: str) -> tuple[str, str]:
    for attempt in range(5):
        try:
            r = session.get(f"{SITE}/{slug}", timeout=60)
            if r.status_code == 200:
                cache_path(slug).write_text(r.text, encoding="utf-8")
                return slug, "ok"
            if r.status_code == 404:
                return slug, "404"
        except requests.RequestException:
            pass
        time.sleep(2 ** attempt)
    return slug, "failed"


def fetch(workers: int = 4) -> None:
    RAW.mkdir(parents=True, exist_ok=True)
    pages = sitemap()
    manifest_file = CACHE / "manifest.json"
    manifest = json.loads(manifest_file.read_text()) if manifest_file.exists() else {}

    todo = [s for s, mod in pages.items()
            if not cache_path(s).exists() or manifest.get(s) != mod]
    print(f"{len(pages)} pages in sitemap, {len(todo)} to download")

    done = 0
    failed = []
    with cf.ThreadPoolExecutor(workers) as pool:
        for slug, status in pool.map(fetch_one, todo):
            done += 1
            if status == "ok":
                manifest[slug] = pages[slug]
            else:
                failed.append((slug, status))
            if done % 100 == 0:
                print(f"  {done}/{len(todo)}")
                manifest_file.write_text(json.dumps(manifest, indent=0))
    manifest_file.write_text(json.dumps(manifest, indent=0))
    (CACHE / "pages.json").write_text(json.dumps(sorted(pages)))
    if failed:
        print("Failed:", failed)


# --------------------------------------------------------------------------- convert

def clean_filename(name: str) -> str:
    name = re.sub(r'[\\/:*?"<>|#^\[\]]', "", name)  # illegal on Windows or meaningful to Obsidian links
    name = re.sub(r"\s+", " ", name).strip(" .")
    return name[:120] or "untitled"


class Page:
    def __init__(self, slug: str, html: str):
        self.slug = slug
        soup = BeautifulSoup(html, "lxml")
        t = soup.select_one("#page-title")
        self.title = t.get_text(" ", strip=True) if t else ""
        if not self.title:
            self.title = slug.split(":")[-1].replace("-", " ").title()
        if slug == "start":
            self.title = "Spheres of Power Wiki"
        elif slug == "nav:side":
            self.title = "Wiki Navigation"
        elif slug == "legal:start":
            self.title = "Legal and Open Game License"
        crumbs = soup.select("#breadcrumbs a")
        self.parents = [a["href"].strip("/") for a in crumbs if a.get("href", "").startswith("/")]
        self.parents = [p for p in self.parents if p != "start"]
        self.tags = [a.get_text(strip=True) for a in soup.select(".page-tags a")
                     if a.get_text(strip=True) and not a.get_text(strip=True).startswith("_")]
        self.body = soup.select_one("#page-content")
        # anchor id -> heading text, so cross-page #toc links can become [[Page#Heading]]
        self.anchors: dict[str, str] = {}
        if self.body:
            for h in self.body.find_all(re.compile("^h[1-6]$")):
                if h.get("id"):
                    self.anchors[h["id"]] = heading_text(h)
            for a in self.body.find_all("a", attrs={"name": True}):
                nxt = a.find_next(re.compile("^h[1-6]$"))
                if nxt:
                    self.anchors[a["name"]] = heading_text(nxt)
        # (target slug, family) for every link the wiki wrapped in a product-line color
        self.colored: list[tuple[str, str]] = []
        if self.body:
            for sp in self.body.find_all("span", style=re.compile("color")):
                m = re.search(r"color:\s*(#[0-9a-fA-F]{6})", sp["style"])
                fam = COLOR_FAMILIES.get(m.group(1).lower()) if m else None
                if not fam:
                    continue
                links = sp.find_all("a", href=True)
                outer = sp.find_parent("a", href=True)
                for a in links + ([outer] if outer else []):
                    target = internal_slug(a["href"])
                    if target:
                        self.colored.append((target, fam))
        self.folder = ""
        self.filename = ""


def internal_slug(href: str) -> str | None:
    """Wikidot page slug an href points to, or None for external/file/anchor links."""
    if not href or href.startswith(("#", "javascript:")):
        return None
    parsed = urllib.parse.urlparse(href)
    if parsed.netloc and not parsed.netloc.endswith("spheresofpower.wikidot.com"):
        return None
    if "local--files" in parsed.path:
        return None
    return urllib.parse.unquote(parsed.path.strip("/")).lower() or "start"


def heading_text(h: Tag) -> str:
    return re.sub(r"[#^\[\]|]", "", h.get_text(" ", strip=True)).strip()


class WikiConverter(MarkdownConverter):
    """markdownify with wikidot-aware link/table/image handling."""

    def __init__(self, page: Page, pages: dict[str, Page], images: dict[str, str],
                 redirects: dict[str, Page] | None = None, **kw):
        super().__init__(heading_style="ATX", bullets="-", escape_underscores=False,
                         escape_asterisks=False, **kw)
        self.page, self.pages, self.images = page, pages, images
        self.redirects = redirects or {}

    # --- links
    def convert_a(self, el, text, *args, **kw):
        href = el.get("href", "")
        text = text.strip()
        if not href or href.startswith("javascript:"):
            return text
        if href.startswith("#"):
            target = self.page.anchors.get(href[1:])
            return f"[[#{target}|{text}]]" if target else text
        parsed = urllib.parse.urlparse(href)
        internal = (not parsed.netloc) or parsed.netloc.endswith("spheresofpower.wikidot.com")
        if internal and "local--files" not in parsed.path:
            slug = urllib.parse.unquote(parsed.path.strip("/")) or "start"
            slug = slug.lower()
            target = self.pages.get(slug) or self.redirects.get(slug)
            if target:
                frag = ""
                if parsed.fragment:
                    h = target.anchors.get(parsed.fragment)
                    frag = f"#{h}" if h else ""
                label = text.replace("|", "\\|").replace("[", "(").replace("]", ")")
                if not label or (label == target.filename and not frag):
                    return f"[[{target.filename}{frag}]]"
                return f"[[{target.filename}{frag}|{label}]]"
            # links to pages that don't exist on the wiki ("red links") -> plain text
            if not parsed.netloc:
                return text
        if not text and el.find("img"):
            return ""  # link around a dropped image (cover art, banners)
        if not href.startswith("http"):
            href = SITE + href
        return f"[{text}]({href})" if text else f"<{href}>"

    # --- images: only kept when downloaded with --images; otherwise dropped entirely
    def convert_img(self, el, text, *args, **kw):
        src = el.get("src", "")
        if src in self.images:
            return f"![[{self.images[src]}]]"
        return ""

    # --- tables: keep cells single-line so the markdown table survives
    def convert_td(self, el, text, *args, **kw):
        text = re.sub(r"\s*\n\s*", " <br> ", text.strip()).replace("|", "\\|")
        text = re.sub(r"(\s*<br>\s*)+$", "", text)
        colspan = int(el.get("colspan", 1) or 1)
        return " " + text + " |" + " |" * (colspan - 1)

    convert_th = convert_td

    # --- column layouts: raw HTML wrappers on their own lines (blank-line separated) so the
    # markdown between them still parses; Quartz styles .sop-columns as a grid, Obsidian
    # simply shows the columns stacked.
    def convert_div(self, el, text, *args, **kw):
        cls = el.get("class") or []
        if "sop-tab-label" in cls:
            return f'\n\n<div class="sop-tab-label">{html.escape(el.get_text(" ", strip=True))}</div>\n\n'
        for name in ("sop-columns", "sop-col", "sop-tabs", "sop-tab"):
            if name in cls:
                if not text.strip():
                    return ""  # every column/link in it was excluded
                extra = f' data-tab="{html.escape(el["data-tab"])}"' if el.get("data-tab") else ""
                return f'\n\n<div class="{name}"{extra}>\n\n{text.strip()}\n\n</div>\n\n'
        return f"\n\n{text}\n\n" if text.strip() else ""


def group_columns(body: Tag, soup_factory) -> None:
    """Wikidot [[div style="float:left; width:N%"]] side-by-side blocks -> .sop-columns/.sop-col."""
    floating = lambda el: isinstance(el, Tag) and el.name == "div" and \
        re.search(r"float:\s*(left|right)", el.get("style", ""))
    for start in body.find_all(floating):
        if start.parent is None or "sop-col" in (start.get("class") or []):
            continue
        prev = start.find_previous_sibling(True)
        if prev is not None and floating(prev):
            continue  # not the first of its run
        run = [start]
        nxt = start.find_next_sibling(True)
        while nxt is not None and floating(nxt):
            run.append(nxt)
            nxt = nxt.find_next_sibling(True)
        if len(run) < 2:
            continue
        wrapper = soup_factory.new_tag("div", attrs={"class": "sop-columns"})
        start.insert_before(wrapper)
        for col in run:
            col.attrs = {"class": "sop-col"}
            wrapper.append(col.extract())


def prune_excluded(body: Tag, excluded: set[str]) -> None:
    """Drop links to excluded book lines from a navigation page, with their tag/separator debris."""
    # whole blocks headed by a link to an excluded hub (e.g. a book's column on the home page)
    for h in body.find_all(["h1", "h2", "h3", "h4"]):
        a = h.find("a", href=True) if h.parent else None
        if a and internal_slug(a["href"]) in excluded:
            block = h.find_parent(lambda t: t.name == "div" and (
                "sop-col" in (t.get("class") or []) or "float" in t.get("style", ""))) or h
            block.decompose()
    for a in body.find_all("a", href=True):
        if a.parent is None or internal_slug(a["href"]) not in excluded:
            continue
        parent = a.parent
        after = a.next_sibling
        before = a.previous_sibling
        is_br = lambda el: isinstance(el, Tag) and el.name == "br"
        # did the link start its line? (only then may its trailing <br> go, or lines would merge)
        line_start = before is None or is_br(before) or (
            isinstance(before, NavigableString) and not before.strip()
            and (before.previous_sibling is None or is_br(before.previous_sibling)))
        if isinstance(after, NavigableString):
            # " [3PP], " / " [DRS] |" etc. that belonged to the removed link
            cleaned = re.sub(r"^\s*(\[[^\]]*\]\s*)*([,|·]\s*)?", "", str(after), count=1)
            after.replace_with(" " + cleaned if cleaned and not line_start else cleaned)
            after = a.next_sibling
        if line_start and is_br(after):
            after.decompose()
        a.decompose()
        if parent.name in ("li", "p", "strong") and not parent.find("a") and \
                not parent.get_text(strip=True).strip(",|·() "):
            parent.decompose()


def drop_excluded_mentions(md: str) -> str:
    """Remove prose sentences that mention an excluded book (e.g. 'X is being added to the wiki')."""
    names = "|".join(re.escape(n) for n in sorted(EXCLUDED_SECTIONS, key=len, reverse=True))
    mention = re.compile(rf"\b({names})\b", re.I)
    out = []
    for line in md.split("\n"):
        if "[[" in line or not mention.search(line):
            out.append(line)
            continue
        sentences = re.split(r"(?<=[.!?])\s+", line)
        kept = [s for s in sentences if not mention.search(s)]
        out.append(" ".join(kept))
    return "\n".join(out)


def rebalance_home_columns(md: str) -> str:
    """Move whole '**Heading**' sections between columns of the home page's main nav grid."""
    lines = md.split("\n")
    heading = lambda l: re.fullmatch(r"\*\*([^*]+)\*\*", l.strip())
    # find the grid that contains the first section we want to move
    wanted = {name for name, _ in HOME_SECTION_MOVES}
    start = None
    for i, l in enumerate(lines):
        if l.strip().startswith('<div class="sop-columns"'):
            start = i
        h = heading(l)
        if h and h.group(1) in wanted and start is not None:
            break
    else:
        return md
    # parse the grid into columns: <div class="sop-col"> ... </div> pairs, then the grid's </div>
    cols: list[list[str]] = []
    cur: list[str] | None = None
    depth = 0  # divs nested inside the current column (e.g. tabs)
    i, end = start + 1, None
    while i < len(lines):
        l = lines[i].strip()
        if l == '<div class="sop-col">' and cur is None:
            cur = []
        elif cur is not None and l.startswith("<div") and not l.endswith("</div>"):
            depth += 1
            cur.append(lines[i])
        elif l == "</div>" and cur is not None and depth:
            depth -= 1
            cur.append(lines[i])
        elif l == "</div>" and cur is not None:
            cols.append(cur)
            cur = None
        elif l == "</div>" and cur is None:
            end = i
            break
        elif cur is not None:
            cur.append(lines[i])
        i += 1
    if end is None:
        return md

    def split_sections(col: list[str]):
        """-> (prefix lines, [(name, lines)]) where a section owns the '---' separator above it."""
        idx = [k for k, l in enumerate(col) if heading(l)]
        if not idx:
            return col, []
        prefix, sections = col[:idx[0]], []
        for n, k in enumerate(idx):
            stop = idx[n + 1] if n + 1 < len(idx) else len(col)
            sections.append([heading(col[k]).group(1), col[k:stop]])
        # hand trailing separators ('---' / blanks) of each section to the next one
        for n in range(len(sections) - 1):
            body = sections[n][1]
            sep = []
            while body and body[-1].strip() in ("", "---"):
                sep.insert(0, body.pop())
            sections[n + 1][1] = sep + sections[n + 1][1]
        return prefix, sections

    parsed = [split_sections(c) for c in cols]
    for name, target in HOME_SECTION_MOVES:
        if target - 1 >= len(parsed):
            continue
        for prefix, sections in parsed:
            hit = next((s for s in sections if s[0] == name), None)
            if hit:
                sections.remove(hit)
                body = [l for l in hit[1]]
                while body and body[0].strip() in ("", "---"):
                    body.pop(0)
                parsed[target - 1][1].append([name, ["", "---", "", *body]])
                break

    rebuilt = []
    for prefix, sections in parsed:
        col = list(prefix)
        for _, body in sections:
            col.extend(body)
        while col and col[-1].strip() in ("", "---"):
            col.pop()
        rebuilt += ['<div class="sop-col">', "", *col, "", "</div>", ""]
    return "\n".join(lines[:start + 1] + [""] + rebuilt + lines[end:])


def set_column_counts(md: str) -> str:
    """Tag each .sop-columns grid with --cols: the number of side-by-side columns it holds.

    Columns containing a markdown table span the full row (see custom.scss), so they don't count;
    the CSS uses --cols to avoid creating empty tracks on wide screens."""
    lines = md.split("\n")
    stack: list[list] = []  # ["grid", line_idx, narrow, total] / ["col", has_table]
    for i, line in enumerate(lines):
        s = line.strip()
        if s.startswith('<div class="sop-columns"'):
            stack.append(["grid", i, 0, 0])
        elif s == '<div class="sop-col">':
            stack.append(["col", False])
        elif s.startswith("<div") and not s.endswith("</div>"):
            stack.append(["other"])  # e.g. tabs; one-line tab labels open and close on one line
        elif s.startswith("| ---") and stack:
            col = next((c for c in reversed(stack) if c[0] == "col"), None)
            if col:
                col[1] = True
        elif s == "</div>" and stack:
            top = stack.pop()
            if top[0] == "other":
                continue
            if top[0] == "col":
                grid = next((g for g in reversed(stack) if g[0] == "grid"), None)
                if grid:
                    grid[3] += 1
                    grid[2] += 0 if top[1] else 1
            else:
                n = top[2] or top[3] or 1
                lines[top[1]] = f'<div class="sop-columns" style="--cols: {n}">'
    return "\n".join(lines)


ARCHETYPE_LINE = re.compile(r"^\*\*([^*\n]+)\*\*\s*\((.*)\)\s*$")


def archetype_tables(md: str) -> str:
    """Runs of '**Class** ([[A]], [[B]] ...)' lines -> a Class | Archetypes | Class Options table.

    On the wiki each class line can be followed by '| [[Alternate Class Features]]'-style lines
    (wikidot's pipe separator); those become the Class Options column."""
    out: list[str] = []
    run: list[dict] = []
    held_blank = 0

    def cell(text: str) -> str:
        text = " ".join(text.split())
        text = re.sub(r"(\s*,\s*){2,}", ", ", text).strip(" ,")
        return re.sub(r"(?<!\\)\|", r"\\|", text)

    def flush():
        if len(run) >= 3:
            options = any(r["extras"] for r in run)
            head = "| Class | Archetypes |" + (" Class Options |" if options else "")
            rows = [head, "| --- | --- |" + (" --- |" if options else "")]
            for r in run:
                if "[[" not in r["arch"] and not r["extras"]:
                    continue  # every archetype was in an excluded book
                row = f"| **{r['cls'].strip()}** | {cell(r['arch'])} |"
                if options:
                    row += " " + " · ".join(cell(e) for e in r["extras"]) + " |"
                rows.append(row)
            out.extend(["", *rows, ""])
        else:
            for r in run:
                out.extend(r["lines"])
        run.clear()

    for line in md.split("\n"):
        stripped = line.strip()
        m = ARCHETYPE_LINE.match(stripped)
        if m:
            run.append({"lines": [line], "cls": m.group(1), "arch": m.group(2), "extras": []})
            held_blank = 0
        elif run and stripped.startswith("|") and not held_blank:
            # continuation of the previous class: "| [[Alchemist Discoveries]]"
            run[-1]["lines"].append(line)
            extra = stripped.lstrip("| ").strip()
            if extra:
                run[-1]["extras"].append(extra)
        elif not stripped and run:
            held_blank += 1  # blank lines between class lines don't end the run
        else:
            flush()
            out.extend([""] * held_blank)
            held_blank = 0
            out.append(line)
    flush()
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out))


def preprocess(body: Tag, soup_factory, excluded: set[str] | None = None) -> None:
    """Rewrite wikidot widgets into plain HTML that markdownify understands."""
    group_columns(body, soup_factory)
    for sel in ["#toc", "script", "style", ".wd-adunit", "iframe", ".page-tags",
                ".footnotes-footer .title", ".printuser"]:
        for el in body.select(sel):
            el.decompose()

    # Tabviews (e.g. Ultimate / Original): .sop-tabs > .sop-tab (label + content). Quartz turns
    # these into clickable tabs (components/SopTabs.tsx); Obsidian shows each label then its content.
    for nav in body.select(".yui-navset"):
        labels = [li.get_text(" ", strip=True) for li in nav.select(".yui-nav li")]
        panes = nav.select(".yui-content > div")
        wrapper = soup_factory.new_tag("div", attrs={"class": "sop-tabs"})
        for label, pane in zip(labels, panes):
            # data-tab lets CSS/JS/Pagefind target a tab by name (pagefind.yml skips "original")
            tab_id = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-") or "tab"
            tab = soup_factory.new_tag("div", attrs={"class": "sop-tab", "data-tab": tab_id})
            name = soup_factory.new_tag("div", attrs={"class": "sop-tab-label"})
            name.string = label
            tab.append(name)
            tab.append(pane)
            wrapper.append(tab)
        nav.replace_with(wrapper)

    # Collapsibles: drop the "show/hide" toggles, keep the unfolded content with its label.
    for block in body.select(".collapsible-block"):
        link = block.select_one(".collapsible-block-folded a")
        label = link.get_text(" ", strip=True) if link else ""
        label = re.sub(r"^[+\-]\s*", "", label)
        content = block.select_one(".collapsible-block-content")
        wrapper = soup_factory.new_tag("div")
        if label and not re.match(r"(?i)^(show|hide)\b", label):
            p = soup_factory.new_tag("p")
            b = soup_factory.new_tag("strong")
            b.string = label
            p.append(b)
            wrapper.append(p)
        if content:
            wrapper.append(content)
        block.replace_with(wrapper)

    # Footnote refs: <sup class="footnoteref"><a>1</a></sup> -> [^1]
    for sup in body.select("sup.footnoteref"):
        sup.replace_with(NavigableString(f"[^{sup.get_text(strip=True)}]"))
    footer = body.select_one(".footnotes-footer")
    if footer:
        lines = []
        for fn in footer.select(".footnote-footer"):
            a = fn.find("a")
            num = a.get_text(strip=True) if a else str(len(lines) + 1)
            if a:
                a.decompose()
            lines.append(f"[^{num}]: {fn.get_text(' ', strip=True).lstrip('. ')}")
        footer.replace_with(NavigableString("\n\n" + "\n".join(lines) + "\n\n" if lines else ""))

    # Wikidot's colored spans / "redtext" etc. are just styling; unwrap.
    for span in body.find_all("span"):
        span.unwrap()
    body.smooth()  # merge text split by the unwrapped spans
    if excluded is not None:
        prune_excluded(body, excluded)

    # Store boxes: cover image linking to a shop + <strong>Book</strong> + price -> "Source: [Book](shop)".
    for img in body.find_all("img"):
        a = img.parent if img.parent and img.parent.name == "a" else None
        if not a or not a.get("href", "").startswith("http"):
            continue
        box = a.parent
        name = a.find_next_sibling("strong")
        if box and box.parent and name and "$" in box.get_text():
            p = soup_factory.new_tag("p")
            em = soup_factory.new_tag("em")
            em.append("Source: ")
            link = soup_factory.new_tag("a", href=a["href"])
            link.string = name.get_text(" ", strip=True)
            em.append(link)
            p.append(em)
            box.replace_with(p)

    # Tables: real data tables stay markdown tables; layout tables and navboxes get flattened.
    for table in reversed(body.find_all("table")):
        if table.parent is None:
            continue
        if is_layout_table(table):
            flatten_table(table, soup_factory)


def is_layout_table(table: Tag) -> bool:
    if "wiki-content-table" not in (table.get("class") or []):
        return True
    rows = table.find_all("tr", recursive=False) or table.select(":scope > tbody > tr")
    widths = [sum(int(c.get("colspan", 1) or 1) for c in r.find_all(["td", "th"], recursive=False))
              for r in rows]
    if not widths or max(widths) < 3:
        return False
    # Navbox: some rows are one cell spanning the table, and the content is basically all links.
    spanning = sum(1 for r in rows if len(r.find_all(["td", "th"], recursive=False)) == 1)
    text = table.get_text(" ", strip=True)
    link_text = " ".join(a.get_text(" ", strip=True) for a in table.find_all("a"))
    return spanning >= 2 and len(link_text) > 0.6 * max(len(text), 1)


def flatten_table(table: Tag, soup_factory) -> None:
    out = soup_factory.new_tag("div")
    rows = table.find_all("tr")
    for tr in rows:
        if tr.find_parent("table") is not table:
            continue
        cells = [c for c in tr.find_all(["td", "th"], recursive=False) if c.get_text(strip=True) or c.find("img")]
        if not cells:
            continue
        if len(cells) == 1:
            cell = cells[0]
            # a lone short cell with no links in a navbox is a section label
            if len(rows) > 1 and not cell.find(["a", "p", "ul", "table"]) and len(cell.get_text(strip=True)) < 60:
                p = soup_factory.new_tag("p")
                b = soup_factory.new_tag("strong")
                b.string = cell.get_text(" ", strip=True)
                p.append(b)
                out.append(p)
            else:
                div = soup_factory.new_tag("div")
                for child in list(cell.contents):
                    div.append(child)
                out.append(div)
        else:
            p = soup_factory.new_tag("p")
            for i, cell in enumerate(cells):
                if i:
                    p.append(" · ")
                for child in list(cell.contents):
                    p.append(child)
            out.append(p)
    table.replace_with(out)


def tidy(md: str) -> str:
    md = md.replace(" ", " ")
    md = re.sub(r"[ \t]+\n", "\n", md)
    md = re.sub(r"\n{3,}", "\n\n", md)
    # markdownify emits "**  text**" when the bold had padding
    md = re.sub(r"\*\*[ \t]+([^*\n]+?)[ \t]*\*\*", r"**\1**", md)
    # "<strong>Prerequisites:</strong>Text" -> bold label must be followed by a space to render
    md = re.sub(r"(\*\*[^*\n]*?[:.]\*\*)(?=[\w(\[])", r"\1 ", md)
    md = archetype_tables(md)
    md = set_column_counts(md)
    return md.strip() + "\n"


def yaml_str(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def assign_paths(pages: dict[str, Page]) -> None:
    """Folder = top-level breadcrumb ancestor's title; filename = page title (deduped)."""
    used: dict[str, str] = {}
    for p in sorted(pages.values(), key=lambda p: p.slug):
        if p.slug == "start":
            p.folder, p.filename = "", "index"
            continue
        if p.slug.startswith(("legal:", "nav:")):
            p.folder = "Meta"
        elif p.parents and p.parents[0] in pages:
            p.folder = clean_filename(pages[p.parents[0]].title)
        else:
            p.folder = ""
        name = clean_filename(p.title)
        if name.lower() in used or name.lower() == "index":
            name = clean_filename(f"{p.title} ({p.slug.replace(':', '-')})")
        used[name.lower()] = p.slug
        p.filename = name
    # Top-level hub pages live inside the folder named after them.
    folders = {p.folder for p in pages.values()}
    for p in pages.values():
        if p.folder or p.slug == "start":
            continue
        if p.filename in folders:
            p.folder = p.filename
        elif "archetype" in p.title.lower():
            p.folder = "Archetypes (Unsorted)"
        else:
            p.folder = "Other Pages"


def download_images(pages: dict[str, Page]) -> dict[str, str]:
    ATTACH.mkdir(parents=True, exist_ok=True)
    mapping = {}
    for p in pages.values():
        if not p.body:
            continue
        for img in p.body.find_all("img"):
            src = img.get("src", "")
            if "local--files" not in src:
                continue
            name = clean_filename(urllib.parse.unquote(src.split("/")[-1]))
            dest = ATTACH / name
            if not dest.exists():
                try:
                    r = session.get(src.replace("http://", "https://"), timeout=60)
                    if r.ok:
                        dest.write_bytes(r.content)
                except requests.RequestException:
                    continue
            if dest.exists():
                mapping[src] = name
    return mapping


def convert(with_images: bool) -> None:
    slugs = [s for s in json.loads((CACHE / "pages.json").read_text())
             if s not in SKIP_EXACT and not s.startswith(SKIP_PREFIXES)]
    pages: dict[str, Page] = {}
    for slug in slugs:
        f = cache_path(slug)
        if f.exists():
            pages[slug] = Page(slug, f.read_text(encoding="utf-8"))
    assign_paths(pages)
    excluded = {s for s, p in pages.items()
                if p.folder in EXCLUDED_SECTIONS or s in EXCLUDED_PAGES
                or any(a in EXCLUDED_PAGES for a in p.parents)}
    for s in excluded:
        del pages[s]
    redirects = old_page_redirects(excluded, pages)
    write_link_families(pages)
    images = download_images(pages) if with_images else {}
    manifest = json.loads((CACHE / "manifest.json").read_text())

    # Remove previously generated notes (but never hand-written ones) so renames don't leave orphans.
    for old in CONTENT.rglob("*.md"):
        try:
            if GENERATED_MARK in old.read_text(encoding="utf-8"):
                old.unlink()
        except OSError:
            pass

    for p in pages.values():
        if not p.body:
            continue
        preprocess(p.body, BeautifulSoup("", "lxml"),
                   excluded - redirects.keys() if p.slug in NAV_PAGES else None)
        md = WikiConverter(p, pages, images, redirects).convert_soup(p.body)
        fm = ["---", f"title: {yaml_str(p.title)}"]
        if p.filename != p.title:
            fm.append(f"aliases: [{yaml_str(p.title)}]")
        tags = sorted({re.sub(r'[^\w/-]', '-', t).strip('-') for t in p.tags} - {""})
        if tags:
            fm.append("tags: [" + ", ".join(yaml_str(t) for t in tags) + "]")
        fm.append(f"source: {SITE}/{p.slug}")
        if manifest.get(p.slug):
            fm.append(f"updated: {manifest[p.slug][:10]}")
        if p.parents:
            fm.append("parent: " + yaml_str(f"[[{pages[p.parents[-1]].filename}]]"
                                            if p.parents[-1] in pages else p.parents[-1]))
        fm.append("---")
        body_md = tidy(md)
        if p.slug in NAV_PAGES:
            body_md = drop_excluded_mentions(body_md)
        if p.slug == "start":
            body_md = rebalance_home_columns(body_md)
        out = "\n".join(fm) + "\n" + GENERATED_MARK + "\n\n" + body_md
        dest = CONTENT / p.folder / f"{p.filename}.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(out, encoding="utf-8")

    # folders emptied by exclusions or renames
    for d in sorted((d for d in CONTENT.rglob("*") if d.is_dir()), key=lambda d: -len(d.parts)):
        if not any(d.iterdir()):
            d.rmdir()

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    (CACHE / "last-convert.txt").write_text(stamp)
    print(f"Wrote {len(pages)} notes to {CONTENT} ({len(excluded)} excluded) ({stamp})")


def old_page_redirects(excluded: set[str], pages: dict[str, Page]) -> dict[str, Page]:
    """Excluded 'old-<x>' pages -> their current page, so links to them keep working."""
    by_title = {p.title.lower(): p for p in pages.values()}
    redirects = {}
    for slug in excluded:
        if not slug.startswith("old-"):
            continue
        current = pages.get(slug[4:]) or by_title.get(slug[4:].replace("-", " "))
        if current:
            redirects[slug] = current
    return redirects


def write_link_families(pages: dict[str, Page]) -> None:
    """Majority-vote each page's product-line color from how the wiki colors links to it."""
    votes: dict[str, Counter] = defaultdict(Counter)
    for p in pages.values():
        for target, fam in p.colored:
            if target in pages:
                votes[target][fam] += 1
    families = {}
    for slug, counts in votes.items():
        t = pages[slug]
        families[f"{t.folder}/{t.filename}.md".lstrip("/")] = counts.most_common(1)[0][0]
    FAMILY_FILE.parent.mkdir(parents=True, exist_ok=True)
    FAMILY_FILE.write_text(json.dumps(dict(sorted(families.items())), indent=1, ensure_ascii=False),
                           encoding="utf-8")

    # Same colors inside Obsidian (Settings -> Appearance -> CSS snippets -> sop-link-colors)
    by_fam: dict[str, list[str]] = defaultdict(list)
    for path, fam in families.items():
        name = Path(path).stem.replace("\\", "\\\\").replace('"', '\\"')
        by_fam[fam] += [f'.internal-link[data-href="{name}"]', f'.internal-link[data-href^="{name}#"]']
    css = ["/* generated by scripts/scrape.py: link colors by product line, matching the wiki */",
           "body { --fam-guile: #6a1fb0; --fam-guile-alt: #a51fe0; --fam-might: #993300; --fam-champion: #008a0e; }",
           ".theme-dark { --fam-guile: #b48cff; --fam-guile-alt: #d88cff; --fam-might: #e8935a; --fam-champion: #6fdc6f; }"]
    for fam, sels in sorted(by_fam.items()):
        css.append(",\n".join(sels) + f" {{ color: var(--fam-{fam}); }}")
    OBSIDIAN_SNIPPET.parent.mkdir(parents=True, exist_ok=True)
    OBSIDIAN_SNIPPET.write_text("\n\n".join(css) + "\n", encoding="utf-8")
    print(f"Link colors for {len(families)} pages: {dict(Counter(families.values()))}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("stage", nargs="?", choices=["fetch", "convert", "all"], default="all")
    ap.add_argument("--images", action="store_true", help="download wiki-hosted images")
    ap.add_argument("--workers", type=int, default=4)
    a = ap.parse_args()
    if a.stage in ("fetch", "all"):
        fetch(a.workers)
    if a.stage in ("convert", "all"):
        convert(a.images)
